source :gemcutter

gem 'aaronh-chronic',       :git => 'git://github.com/AaronH/chronic.git', :require => 'chronic'
gem 'amatch'
gem 'beanstalk-client'
gem 'bson'
gem 'bson_ext'
gem 'cancan'
gem 'carrierwave',          :git => 'git://github.com/jnicklas/carrierwave.git'
gem 'compass'
gem 'data_objects'
gem 'do_postgres'
gem 'delayed_job'
gem 'delayed_job_mongoid'
gem 'devise'
gem 'gravtastic'
gem 'haml'
gem 'has_constant'
gem 'has_scope'
gem 'hassle',               :git => 'git://github.com/koppen/hassle.git'
gem 'inherited_resources'
gem 'mail'
gem 'memcached'
gem 'mongo'
gem 'mongo_session_store',  :git => 'git://github.com/mattbeedle/mongo_session_store.git'
gem 'mongoid',              :git => 'git://github.com/mattbeedle/mongoid.git', :branch => 'development'
gem 'navvy'
gem 'pg'
gem 'rack-gridfs',          :require => 'rack/gridfs', :git => 'git://github.com/mattbeedle/rack-gridfs.git'
gem 'rails'
gem 'remail'
gem 'riddle'
gem 'salesflip-lead_notifications', :require => 'lead_notifications'
gem 'simple_form'
gem 'sqlite3-ruby',         :require => 'sqlite3'
gem 'sunspot',              :require => 'sunspot'
gem 'sunspot_mongoid',      :git => 'git://github.com/jugyo/sunspot_mongoid.git'
gem 'sunspot_rails'
gem 'uuid'
gem 'warden'
gem 'will_paginate',        '3.0.pre'

group :production do
  gem 'smurf'
  gem 'mbeedle-heroku-autoscale', :require => 'heroku/autoscale'
end

group :development do
  gem 'wirble'
  gem 'heroku'
  gem 'thin'
end

group :test do
  gem 'pickle'
  gem 'pickle-mongoid'
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'spork'
  gem 'launchy'
  gem 'machinist_mongo',  :require => 'machinist/mongoid'
  gem 'autotest-rails',   :require => 'autotest/rails'
  gem 'fakeweb'
  gem 'mocha'
  gem 'faker'
  gem 'shoulda'
  gem 'database_cleaner'
  gem 'timecop'
end
